<?php
$root = dirname(__DIR__);
$style = file_get_contents($root . '/style.css');
$functions = file_get_contents($root . '/functions.php');
assert(str_contains($style, 'Theme Name: Suka News Tiga'));
assert(!str_contains($functions, "inc/suka-options.php"));
assert(str_contains($functions, "function_exists( 'suka_core_get_post_views' )"));
assert(!str_contains($functions, 'function suka_news_satu_get_views'));
assert(!str_contains($functions, 'function suka_news_satu_get_ads'));
$header = file_get_contents($root . '/header.php');
$footer = file_get_contents($root . '/footer.php');
assert(str_contains($header, "suka_core_get_banners( 'header' )"));
assert(strpos($header, 'header-secondary-navigation') < strpos($header, 'site-logo'));
assert(strpos($header, 'header-ad') < strpos($header, 'primary-navigation'));
assert(strpos($header, 'primary-navigation') < strpos($header, 'header-social'));
assert(str_contains($header, 'suka_news_satu_get_social_links'));
assert(!str_contains($functions, "'suka_news_satu_header_social'"));
assert(str_contains($functions, 'suka_news_satu_social_color_'));
assert(str_contains($header, 'header-social__link--'));
assert(str_contains($style, '.header-social__link--facebook'));
assert(str_contains($style, '--social-color: #1877f2;'));
assert(str_contains($functions, "'title'       => __( 'Footer dan Akun Sosial'"));
assert(str_contains($style, '.news-ticker__label'));
assert(str_contains($style, 'background: var(--color-accent);'));
assert(str_contains($style, '.header-navigation__inner'));
assert(str_contains($style, '.header-social'));
assert(str_contains($style, '.news-category,
.home-main-slider__content .news-category'));
assert(str_contains($style, '.header-top {
		display: block;'));
assert(str_contains($style, 'grid-template-columns: 1fr auto;'));
assert(str_contains($style, 'gap: 0;'));
assert(str_contains($style, '.home-main {
		order: -1;'));
assert(str_contains($style, 'color: #fff;'));
assert(str_contains($header, 'news-ticker'));
assert(str_contains($header, 'news-ticker__items'));
assert(str_contains($header, "'posts_per_page' => 8"));
assert(str_contains($style, '.news-ticker__label'));
assert(str_contains($style, '.mobile-secondary-menu a:hover'));
assert(str_contains($style, "display: flex;\n\t\tflex-wrap: wrap;"));
assert(str_contains($style, 'justify-content: center;'));
assert(str_contains($style, '.mobile-secondary-menu li:not(:last-child)::after'));
assert(strpos($header, 'mobile-secondary-navigation') < strpos($header, "'theme_location' => 'primary'"));
assert(str_contains($style, '.news-ticker__label { margin-left: 0;'));
assert(substr_count($header, "'theme_location' => 'secondary'") === 2);
assert(substr_count($footer, "'theme_location' => 'secondary'") === 1);
assert(str_contains(file_get_contents($root . '/sidebar.php'), "suka_core_get_banners( 'sidebar' )"));
assert(str_contains(file_get_contents($root . '/sidebar.php'), 'home-latest-sidebar-item__thumb'));
assert(!str_contains(file_get_contents($root . '/sidebar.php'), 'suka_news_satu_get_news_meta'));
assert(!str_contains(file_get_contents($root . '/sidebar.php'), 'Top Kategori'));
assert(str_contains(file_get_contents($root . '/front-page.php'), "suka_core_get_banners( 'feed' )"));
assert(str_contains($functions, 'function suka_news_satu_get_news_meta'));
$front = file_get_contents($root . '/front-page.php');
assert(str_contains($front, 'home-grid'));
assert(str_contains($front, 'home-left-list'));
assert(str_contains($front, 'home-main-slider'));
assert(str_contains($front, 'home-slider-slide'));
assert(str_contains($front, 'data-slide'));
assert(str_contains($style, '.home-slider-slide.is-active'));
assert(str_contains($style, 'min-height: 520px;'));
assert(str_contains(file_get_contents($root . '/assets/js/theme.js'), 'home-main-slider'));
assert(str_contains(file_get_contents($root . '/assets/js/theme.js'), 'setInterval'));
assert(str_contains($style, 'border-left: 1px solid #e2e8f0;'));
assert(str_contains($style, 'background: var(--color-accent);'));
assert(str_contains($style, 'padding: 0.32rem 0.7rem;'));
assert(str_contains($style, 'border-radius: 999px;'));
assert(str_contains($style, 'box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--color-accent) 22%, transparent);'));
assert(str_contains($style, '.home-main-slider__content .news-category'));
assert(str_contains($style, '.home-main time {'));
assert(str_contains($style, 'font-weight: 700;'));
assert(str_contains($front, 'home-slider-thumbs'));
assert(str_contains($front, 'home-feed-grid'));
assert(!str_contains(substr($front, strpos($front, 'home-feed-grid'), strpos($front, 'home-row-two') - strpos($front, 'home-feed-grid')), 'suka_news_satu_get_category_bubbles'));
assert(str_contains($front, 'home-right-list'));
assert(str_contains($front, 'home-row-two'));
assert(str_contains($front, 'home-main-news'));
assert(!str_contains($front, 'Berita Video'));
assert(str_contains($front, 'home-video-card__category'));
assert(str_contains($front, 'home-row-sidebar'));
assert(str_contains($front, "suka_core_get_banners( 'sidebar' )"));
assert(str_contains($style, 'grid-template-columns: minmax(0, 2fr) minmax(280px, 1fr);'));
assert(str_contains($style, '.home-video-card'));
assert(str_contains($style, '.home-video-card__category .news-category'));
assert(str_contains($style, 'background: var(--color-accent);'));
assert(str_contains($style, '.home-sidebar-ad'));
assert(str_contains($front, 'home-latest-sidebar-item__thumb'));
assert(str_contains($style, '.home-latest-sidebar-item {
	display: grid;'));
assert(str_contains($style, 'grid-template-columns: 88px 1fr;'));
assert(str_contains($style, '.header-ad__item + .header-ad__item'));
assert(str_contains($style, 'margin-top: 0.75rem;'));
assert(str_contains($front, 'array_slice( $posts, 13, 10 )'));
assert(str_contains($style, '.home-main-news-list {
	display: grid;
	gap: 1rem;
}'));
assert(str_contains($style, '.home-row-sidebar {
	position: sticky;'));
assert(!str_contains(substr($front, strpos($front, 'home-right-list'), strpos($front, 'home-row-two') - strpos($front, 'home-right-list')), 'suka_news_satu_get_category_bubbles'));
assert(str_contains($style, 'grid-template-columns: minmax(0, 20fr) minmax(0, 60fr) minmax(0, 20fr);'));
assert(str_contains($style, '.home-feed-grid'));
$single = file_get_contents($root . '/single.php');
$feed = file_get_contents($root . '/template-parts/content-feed.php');
assert(str_contains($feed, 'wp_trim_words( get_the_excerpt(), 12'));
assert(!str_contains($feed, '<?php the_excerpt(); ?>'));
assert(str_contains($single, 'suka_core_render_share_buttons'));
assert(str_contains($single, 'suka_core_get_share_position'));
assert(str_contains($style, '.article-share--icons b'));
assert(str_contains($style, '.article-share--labels b'));
assert(!str_contains($style, ".article-byline,\n\t.article-share {"));
assert(str_contains($style, "@media (max-width: 780px)"));
assert(str_contains($style, ".site-logo {\n\t\tjustify-content: center;"));
assert(!str_contains($single, 'facebook.com/sharer'));
assert(!str_contains($functions, 'suka_news_satu_track_post_view'));
assert(!str_contains($functions, 'suka_news_satu_sanitize_ad_gallery'));
assert(!str_contains($functions, 'class-ad-gallery-control.php'));
assert(!str_contains($functions, 'customizer-ads.css'));
assert(!str_contains($functions, 'customizer-ads.js'));

assert(str_contains($style, '.single-layout {'));
assert(str_contains($style, '.archive-card'));
assert(str_contains($style, '.static-page'));
assert(str_contains($style, '.error-latest-grid'));
assert(str_contains($style, '.site-sidebar {'));
assert(str_contains($style, '.news-meta {
	display: flex;
	align-items: center;
	flex-wrap: wrap;
	gap: 0.35rem 0.75rem;'));
assert(!str_contains($style, '.single-article .news-views'));
assert(str_contains($style, 'position: sticky;'));
assert(str_contains($style, 'box-shadow: 0 16px 40px rgba(15, 23, 42, 0.08);'));
assert(str_contains(file_get_contents($root . '/single.php'), 'article-featured-image'));
assert(str_contains($style, '.single-article .news-categories'));
assert(str_contains($style, 'margin-bottom: 0.9rem;'));
assert(str_contains($style, 'flex-wrap: wrap;'));
assert(str_contains(file_get_contents($root . '/archive.php'), 'archive-layout'));
assert(str_contains(file_get_contents($root . '/404.php'), 'error-page__latest'));
echo "PASS: Suka News Tiga contract\n";
